// Vendored from zpaq-flutter by tool/sync_zpaq.sh: do not edit here, change
// zpaq-flutter and sync again. Pure Dart port of libzpaq and zpaq 7.15 (Matt
// Mahoney, public domain) with the zpaqfranz attribute format (Franco
// Corbelli, MIT). Copyright (c) 2026 Max Brito, BSD 3-clause; see LICENSE
// for the license and the third party notices.

// GENERATED by tool/gen_hcomp.dart. Do not edit.
// ignore_for_file: unused_local_variable, dead_code, curly_braces_in_flow_control_structures, prefer_final_locals, unnecessary_statements, unused_element, no_leading_underscores_for_local_identifiers

part of 'zpaql.dart';

/// The translated program for HCOMP [code][start..end), or null.
void Function(Zpaql, int)? _nativeHcomp(Uint8List code, int start, int end) {
  final n = end - start;
  if (n == 18 && _same(code, start, _code0)) return _hc0;
  if (n == 85 && _same(code, start, _code1)) return _hc1;
  if (n == 44 && _same(code, start, _code2)) return _hc2;
  if (n == 68 && _same(code, start, _code3)) return _hc3;
  if (n == 76 && _same(code, start, _code4)) return _hc4;
  if (n == 205 && _same(code, start, _code5)) return _hc5;
  if (n == 171 && _same(code, start, _code6)) return _hc6;
  if (n == 85 && _same(code, start, _code7)) return _hc7;
  if (n == 76 && _same(code, start, _code8)) return _hc8;
  return null;
}

bool _same(Uint8List code, int start, List<int> ref) {
  for (var i = 0; i < ref.length; ++i) {
    if (code[start + i] != ref[i]) return false;
  }
  return true;
}

const List<int> _code0 = [
  18,
  104,
  135,
  255,
  88,
  114,
  95,
  0,
  52,
  95,
  0,
  74,
  70,
  25,
  59,
  112,
  56,
  0
];
@pragma('vm:unsafe:no-bounds-checks')
void _hc0(Zpaql z, int input) {
  final m = z._m, h = z._h, r = z._r;
  final mm = z._mmask, hm = z._hmask;
  var a = input & _m32, b = z._b, c = z._c, d = z._d, f = z._f;
  int x;
  c = (c - 1) & _m32;
  m[c & mm] = a;
  a = (a + 255) & _m32;
  d = a;
  h[d & hm] = c;
  d = 0;
  h[d & hm] = 0;
  d = 0;
  b = c;
  a = h[d & hm];
  d = (d + 1) & _m32;
  a = ((a + m[b & mm] + 512) * 773) & _m32;
  h[d & hm] = a;
  z._a = a;
  z._b = b;
  z._c = c;
  z._d = d;
  z._f = f;
  return;
  z._err();
  z._err();
}

const List<int> _code1 = [
  18,
  104,
  135,
  255,
  88,
  114,
  7,
  1,
  223,
  0,
  47,
  4,
  71,
  111,
  63,
  22,
  223,
  1,
  47,
  17,
  69,
  55,
  2,
  239,
  63,
  47,
  6,
  215,
  6,
  1,
  1,
  63,
  2,
  1,
  1,
  63,
  1,
  2,
  55,
  1,
  95,
  0,
  52,
  74,
  7,
  1,
  239,
  1,
  47,
  18,
  7,
  2,
  231,
  64,
  47,
  4,
  68,
  60,
  63,
  6,
  215,
  6,
  60,
  7,
  1,
  60,
  63,
  6,
  71,
  255,
  60,
  7,
  2,
  60,
  95,
  0,
  74,
  70,
  25,
  59,
  9,
  59,
  112,
  56,
  0
];
@pragma('vm:unsafe:no-bounds-checks')
void _hc1(Zpaql z, int input) {
  final m = z._m, h = z._h, r = z._r;
  final mm = z._mmask, hm = z._hmask;
  var a = input & _m32, b = z._b, c = z._c, d = z._d, f = z._f;
  int x;
  var blk = 0;
  while (true) {
    switch (blk) {
      case 0:
        c = (c - 1) & _m32;
        m[c & mm] = a;
        a = (a + 255) & _m32;
        d = a;
        h[d & hm] = c;
        a = r[1];
        f = a == 0 ? 1 : 0;
        if (f == 0) {
          blk = 16;
          continue;
        }
        blk = 12;
        continue;
      case 12:
        a = 111;
        blk = 38;
        continue;
        blk = 16;
        continue;
      case 16:
        f = a == 1 ? 1 : 0;
        if (f == 0) {
          blk = 37;
          continue;
        }
        blk = 20;
        continue;
      case 20:
        a = m[c & mm];
        r[2] = a;
        f = a > 63 ? 1 : 0;
        if (f == 0) {
          blk = 33;
          continue;
        }
        blk = 27;
        continue;
      case 27:
        a >>= (6 & 31);
        a = (a + 1) & _m32;
        a = (a + 1) & _m32;
        blk = 35;
        continue;
        blk = 33;
        continue;
      case 33:
        a = (a + 1) & _m32;
        a = (a + 1) & _m32;
        blk = 35;
        continue;
      case 35:
        blk = 38;
        continue;
        blk = 37;
        continue;
      case 37:
        a = (a - 1) & _m32;
        blk = 38;
        continue;
      case 38:
        r[1] = a;
        d = 0;
        h[d & hm] = 0;
        b = c;
        a = r[1];
        f = a > 1 ? 1 : 0;
        if (f == 0) {
          blk = 68;
          continue;
        }
        blk = 50;
        continue;
      case 50:
        a = r[2];
        f = a < 64 ? 1 : 0;
        if (f == 0) {
          blk = 60;
          continue;
        }
        blk = 56;
        continue;
      case 56:
        a = m[b & mm];
        h[d & hm] = (h[d & hm] + a + 512) * 773;
        blk = 66;
        continue;
        blk = 60;
        continue;
      case 60:
        a >>= (6 & 31);
        h[d & hm] = (h[d & hm] + a + 512) * 773;
        a = r[1];
        h[d & hm] = (h[d & hm] + a + 512) * 773;
        blk = 66;
        continue;
      case 66:
        blk = 74;
        continue;
        blk = 68;
        continue;
      case 68:
        a = 255;
        h[d & hm] = (h[d & hm] + a + 512) * 773;
        a = r[2];
        h[d & hm] = (h[d & hm] + a + 512) * 773;
        blk = 74;
        continue;
      case 74:
        d = 0;
        b = c;
        a = h[d & hm];
        d = (d + 1) & _m32;
        a = ((a + m[b & mm] + 512) * 773) & _m32;
        b = (b + 1) & _m32;
        a = ((a + m[b & mm] + 512) * 773) & _m32;
        h[d & hm] = a;
        z._a = a;
        z._b = b;
        z._c = c;
        z._d = d;
        z._f = f;
        return;
        z._err();
        z._err();
    }
  }
}

const List<int> _code2 = [
  18,
  104,
  135,
  255,
  88,
  114,
  95,
  0,
  52,
  95,
  0,
  74,
  70,
  25,
  59,
  9,
  112,
  25,
  59,
  9,
  112,
  25,
  59,
  9,
  112,
  25,
  59,
  9,
  112,
  25,
  59,
  9,
  59,
  112,
  95,
  6,
  70,
  151,
  24,
  133,
  1,
  112,
  56,
  0
];
@pragma('vm:unsafe:no-bounds-checks')
void _hc2(Zpaql z, int input) {
  final m = z._m, h = z._h, r = z._r;
  final mm = z._mmask, hm = z._hmask;
  var a = input & _m32, b = z._b, c = z._c, d = z._d, f = z._f;
  int x;
  c = (c - 1) & _m32;
  m[c & mm] = a;
  a = (a + 255) & _m32;
  d = a;
  h[d & hm] = c;
  d = 0;
  h[d & hm] = 0;
  d = 0;
  b = c;
  a = h[d & hm];
  d = (d + 1) & _m32;
  a = ((a + m[b & mm] + 512) * 773) & _m32;
  b = (b + 1) & _m32;
  h[d & hm] = a;
  d = (d + 1) & _m32;
  a = ((a + m[b & mm] + 512) * 773) & _m32;
  b = (b + 1) & _m32;
  h[d & hm] = a;
  d = (d + 1) & _m32;
  a = ((a + m[b & mm] + 512) * 773) & _m32;
  b = (b + 1) & _m32;
  h[d & hm] = a;
  d = (d + 1) & _m32;
  a = ((a + m[b & mm] + 512) * 773) & _m32;
  b = (b + 1) & _m32;
  h[d & hm] = a;
  d = (d + 1) & _m32;
  a = ((a + m[b & mm] + 512) * 773) & _m32;
  b = (b + 1) & _m32;
  a = ((a + m[b & mm] + 512) * 773) & _m32;
  h[d & hm] = a;
  d = 6;
  a = h[d & hm];
  a = (a * 24) & _m32;
  a = (a + m[c & mm]) & _m32;
  a = (a + 1) & _m32;
  h[d & hm] = a;
  z._a = a;
  z._b = b;
  z._c = c;
  z._d = d;
  z._f = f;
  return;
  z._err();
  z._err();
}

const List<int> _code3 = [
  18,
  104,
  135,
  255,
  88,
  114,
  95,
  0,
  52,
  95,
  0,
  74,
  70,
  25,
  59,
  9,
  112,
  25,
  59,
  9,
  112,
  25,
  59,
  9,
  112,
  25,
  59,
  9,
  112,
  25,
  59,
  9,
  59,
  112,
  95,
  6,
  70,
  151,
  24,
  133,
  1,
  112,
  69,
  175,
  223,
  143,
  65,
  175,
  255,
  231,
  26,
  47,
  10,
  95,
  7,
  70,
  151,
  20,
  133,
  1,
  112,
  63,
  3,
  95,
  7,
  52,
  56,
  0
];
@pragma('vm:unsafe:no-bounds-checks')
void _hc3(Zpaql z, int input) {
  final m = z._m, h = z._h, r = z._r;
  final mm = z._mmask, hm = z._hmask;
  var a = input & _m32, b = z._b, c = z._c, d = z._d, f = z._f;
  int x;
  var blk = 0;
  while (true) {
    switch (blk) {
      case 0:
        c = (c - 1) & _m32;
        m[c & mm] = a;
        a = (a + 255) & _m32;
        d = a;
        h[d & hm] = c;
        d = 0;
        h[d & hm] = 0;
        d = 0;
        b = c;
        a = h[d & hm];
        d = (d + 1) & _m32;
        a = ((a + m[b & mm] + 512) * 773) & _m32;
        b = (b + 1) & _m32;
        h[d & hm] = a;
        d = (d + 1) & _m32;
        a = ((a + m[b & mm] + 512) * 773) & _m32;
        b = (b + 1) & _m32;
        h[d & hm] = a;
        d = (d + 1) & _m32;
        a = ((a + m[b & mm] + 512) * 773) & _m32;
        b = (b + 1) & _m32;
        h[d & hm] = a;
        d = (d + 1) & _m32;
        a = ((a + m[b & mm] + 512) * 773) & _m32;
        b = (b + 1) & _m32;
        h[d & hm] = a;
        d = (d + 1) & _m32;
        a = ((a + m[b & mm] + 512) * 773) & _m32;
        b = (b + 1) & _m32;
        a = ((a + m[b & mm] + 512) * 773) & _m32;
        h[d & hm] = a;
        d = 6;
        a = h[d & hm];
        a = (a * 24) & _m32;
        a = (a + m[c & mm]) & _m32;
        a = (a + 1) & _m32;
        h[d & hm] = a;
        a = m[c & mm];
        a &= 223;
        a = (a - 65) & _m32;
        a &= 255;
        f = a < 26 ? 1 : 0;
        if (f == 0) {
          blk = 63;
          continue;
        }
        blk = 53;
        continue;
      case 53:
        d = 7;
        a = h[d & hm];
        a = (a * 20) & _m32;
        a = (a + m[c & mm]) & _m32;
        a = (a + 1) & _m32;
        h[d & hm] = a;
        blk = 66;
        continue;
        blk = 63;
        continue;
      case 63:
        d = 7;
        h[d & hm] = 0;
        blk = 66;
        continue;
      case 66:
        z._a = a;
        z._b = b;
        z._c = c;
        z._d = d;
        z._f = f;
        return;
        z._err();
        z._err();
    }
  }
}

const List<int> _code4 = [
  18,
  104,
  135,
  255,
  88,
  114,
  7,
  1,
  223,
  0,
  47,
  4,
  71,
  111,
  63,
  22,
  223,
  1,
  47,
  17,
  69,
  55,
  2,
  239,
  63,
  47,
  6,
  215,
  6,
  1,
  1,
  63,
  2,
  1,
  1,
  63,
  1,
  2,
  55,
  1,
  95,
  0,
  52,
  74,
  7,
  1,
  239,
  1,
  47,
  18,
  7,
  2,
  231,
  64,
  47,
  4,
  68,
  60,
  63,
  6,
  215,
  6,
  60,
  7,
  1,
  60,
  63,
  6,
  71,
  255,
  60,
  7,
  2,
  60,
  56,
  0
];
@pragma('vm:unsafe:no-bounds-checks')
void _hc4(Zpaql z, int input) {
  final m = z._m, h = z._h, r = z._r;
  final mm = z._mmask, hm = z._hmask;
  var a = input & _m32, b = z._b, c = z._c, d = z._d, f = z._f;
  int x;
  var blk = 0;
  while (true) {
    switch (blk) {
      case 0:
        c = (c - 1) & _m32;
        m[c & mm] = a;
        a = (a + 255) & _m32;
        d = a;
        h[d & hm] = c;
        a = r[1];
        f = a == 0 ? 1 : 0;
        if (f == 0) {
          blk = 16;
          continue;
        }
        blk = 12;
        continue;
      case 12:
        a = 111;
        blk = 38;
        continue;
        blk = 16;
        continue;
      case 16:
        f = a == 1 ? 1 : 0;
        if (f == 0) {
          blk = 37;
          continue;
        }
        blk = 20;
        continue;
      case 20:
        a = m[c & mm];
        r[2] = a;
        f = a > 63 ? 1 : 0;
        if (f == 0) {
          blk = 33;
          continue;
        }
        blk = 27;
        continue;
      case 27:
        a >>= (6 & 31);
        a = (a + 1) & _m32;
        a = (a + 1) & _m32;
        blk = 35;
        continue;
        blk = 33;
        continue;
      case 33:
        a = (a + 1) & _m32;
        a = (a + 1) & _m32;
        blk = 35;
        continue;
      case 35:
        blk = 38;
        continue;
        blk = 37;
        continue;
      case 37:
        a = (a - 1) & _m32;
        blk = 38;
        continue;
      case 38:
        r[1] = a;
        d = 0;
        h[d & hm] = 0;
        b = c;
        a = r[1];
        f = a > 1 ? 1 : 0;
        if (f == 0) {
          blk = 68;
          continue;
        }
        blk = 50;
        continue;
      case 50:
        a = r[2];
        f = a < 64 ? 1 : 0;
        if (f == 0) {
          blk = 60;
          continue;
        }
        blk = 56;
        continue;
      case 56:
        a = m[b & mm];
        h[d & hm] = (h[d & hm] + a + 512) * 773;
        blk = 66;
        continue;
        blk = 60;
        continue;
      case 60:
        a >>= (6 & 31);
        h[d & hm] = (h[d & hm] + a + 512) * 773;
        a = r[1];
        h[d & hm] = (h[d & hm] + a + 512) * 773;
        blk = 66;
        continue;
      case 66:
        blk = 74;
        continue;
        blk = 68;
        continue;
      case 68:
        a = 255;
        h[d & hm] = (h[d & hm] + a + 512) * 773;
        a = r[2];
        h[d & hm] = (h[d & hm] + a + 512) * 773;
        blk = 74;
        continue;
      case 74:
        z._a = a;
        z._b = b;
        z._c = c;
        z._d = d;
        z._f = f;
        return;
        z._err();
        z._err();
    }
  }
}

const List<int> _code5 = [
  18,
  104,
  135,
  255,
  88,
  114,
  69,
  175,
  223,
  143,
  65,
  175,
  255,
  231,
  26,
  47,
  17,
  95,
  0,
  70,
  151,
  20,
  133,
  1,
  112,
  25,
  70,
  151,
  20,
  133,
  1,
  112,
  63,
  8,
  95,
  0,
  70,
  25,
  112,
  95,
  0,
  52,
  95,
  2,
  52,
  71,
  255,
  135,
  10,
  88,
  70,
  138,
  239,
  255,
  47,
  2,
  71,
  255,
  95,
  2,
  60,
  74,
  68,
  60,
  95,
  2,
  74,
  70,
  25,
  59,
  112,
  95,
  4,
  52,
  95,
  5,
  52,
  95,
  5,
  74,
  70,
  25,
  59,
  9,
  112,
  25,
  59,
  9,
  112,
  25,
  59,
  9,
  112,
  25,
  59,
  9,
  112,
  25,
  59,
  9,
  112,
  25,
  59,
  9,
  112,
  25,
  59,
  9,
  59,
  112,
  95,
  13,
  70,
  151,
  24,
  133,
  1,
  112,
  95,
  14,
  52,
  66,
  175,
  1,
  60,
  74,
  9,
  68,
  60,
  95,
  14,
  74,
  70,
  25,
  59,
  112,
  95,
  16,
  52,
  66,
  167,
  3,
  60,
  74,
  9,
  9,
  68,
  60,
  95,
  16,
  74,
  70,
  25,
  59,
  112,
  95,
  18,
  52,
  66,
  175,
  3,
  60,
  74,
  9,
  9,
  9,
  68,
  60,
  95,
  18,
  74,
  70,
  25,
  59,
  112,
  95,
  21,
  52,
  74,
  4,
  207,
  8,
  132,
  207,
  8,
  112,
  95,
  23,
  52,
  74,
  4,
  207,
  8,
  132,
  9,
  207,
  8,
  132,
  215,
  5,
  207,
  8,
  112,
  56,
  0
];
@pragma('vm:unsafe:no-bounds-checks')
void _hc5(Zpaql z, int input) {
  final m = z._m, h = z._h, r = z._r;
  final mm = z._mmask, hm = z._hmask;
  var a = input & _m32, b = z._b, c = z._c, d = z._d, f = z._f;
  int x;
  var blk = 0;
  while (true) {
    switch (blk) {
      case 0:
        c = (c - 1) & _m32;
        m[c & mm] = a;
        a = (a + 255) & _m32;
        d = a;
        h[d & hm] = c;
        a = m[c & mm];
        a &= 223;
        a = (a - 65) & _m32;
        a &= 255;
        f = a < 26 ? 1 : 0;
        if (f == 0) {
          blk = 34;
          continue;
        }
        blk = 17;
        continue;
      case 17:
        d = 0;
        a = h[d & hm];
        a = (a * 20) & _m32;
        a = (a + m[c & mm]) & _m32;
        a = (a + 1) & _m32;
        h[d & hm] = a;
        d = (d + 1) & _m32;
        a = h[d & hm];
        a = (a * 20) & _m32;
        a = (a + m[c & mm]) & _m32;
        a = (a + 1) & _m32;
        h[d & hm] = a;
        blk = 42;
        continue;
        blk = 34;
        continue;
      case 34:
        d = 0;
        a = h[d & hm];
        d = (d + 1) & _m32;
        h[d & hm] = a;
        d = 0;
        h[d & hm] = 0;
        blk = 42;
        continue;
      case 42:
        d = 2;
        h[d & hm] = 0;
        a = 255;
        a = (a + 10) & _m32;
        d = a;
        a = h[d & hm];
        a = (a - c) & _m32;
        f = a > 255 ? 1 : 0;
        if (f == 0) {
          blk = 58;
          continue;
        }
        blk = 56;
        continue;
      case 56:
        a = 255;
        blk = 58;
        continue;
      case 58:
        d = 2;
        h[d & hm] = (h[d & hm] + a + 512) * 773;
        b = c;
        a = m[b & mm];
        h[d & hm] = (h[d & hm] + a + 512) * 773;
        d = 2;
        b = c;
        a = h[d & hm];
        d = (d + 1) & _m32;
        a = ((a + m[b & mm] + 512) * 773) & _m32;
        h[d & hm] = a;
        d = 4;
        h[d & hm] = 0;
        d = 5;
        h[d & hm] = 0;
        d = 5;
        b = c;
        a = h[d & hm];
        d = (d + 1) & _m32;
        a = ((a + m[b & mm] + 512) * 773) & _m32;
        b = (b + 1) & _m32;
        h[d & hm] = a;
        d = (d + 1) & _m32;
        a = ((a + m[b & mm] + 512) * 773) & _m32;
        b = (b + 1) & _m32;
        h[d & hm] = a;
        d = (d + 1) & _m32;
        a = ((a + m[b & mm] + 512) * 773) & _m32;
        b = (b + 1) & _m32;
        h[d & hm] = a;
        d = (d + 1) & _m32;
        a = ((a + m[b & mm] + 512) * 773) & _m32;
        b = (b + 1) & _m32;
        h[d & hm] = a;
        d = (d + 1) & _m32;
        a = ((a + m[b & mm] + 512) * 773) & _m32;
        b = (b + 1) & _m32;
        h[d & hm] = a;
        d = (d + 1) & _m32;
        a = ((a + m[b & mm] + 512) * 773) & _m32;
        b = (b + 1) & _m32;
        h[d & hm] = a;
        d = (d + 1) & _m32;
        a = ((a + m[b & mm] + 512) * 773) & _m32;
        b = (b + 1) & _m32;
        a = ((a + m[b & mm] + 512) * 773) & _m32;
        h[d & hm] = a;
        d = 13;
        a = h[d & hm];
        a = (a * 24) & _m32;
        a = (a + m[c & mm]) & _m32;
        a = (a + 1) & _m32;
        h[d & hm] = a;
        d = 14;
        h[d & hm] = 0;
        a = c;
        a &= 1;
        h[d & hm] = (h[d & hm] + a + 512) * 773;
        b = c;
        b = (b + 1) & _m32;
        a = m[b & mm];
        h[d & hm] = (h[d & hm] + a + 512) * 773;
        d = 14;
        b = c;
        a = h[d & hm];
        d = (d + 1) & _m32;
        a = ((a + m[b & mm] + 512) * 773) & _m32;
        h[d & hm] = a;
        d = 16;
        h[d & hm] = 0;
        a = c;
        x = 3;
        a = x != 0 ? a % x : 0;
        h[d & hm] = (h[d & hm] + a + 512) * 773;
        b = c;
        b = (b + 1) & _m32;
        b = (b + 1) & _m32;
        a = m[b & mm];
        h[d & hm] = (h[d & hm] + a + 512) * 773;
        d = 16;
        b = c;
        a = h[d & hm];
        d = (d + 1) & _m32;
        a = ((a + m[b & mm] + 512) * 773) & _m32;
        h[d & hm] = a;
        d = 18;
        h[d & hm] = 0;
        a = c;
        a &= 3;
        h[d & hm] = (h[d & hm] + a + 512) * 773;
        b = c;
        b = (b + 1) & _m32;
        b = (b + 1) & _m32;
        b = (b + 1) & _m32;
        a = m[b & mm];
        h[d & hm] = (h[d & hm] + a + 512) * 773;
        d = 18;
        b = c;
        a = h[d & hm];
        d = (d + 1) & _m32;
        a = ((a + m[b & mm] + 512) * 773) & _m32;
        h[d & hm] = a;
        d = 21;
        h[d & hm] = 0;
        b = c;
        a = 0;
        a = (a << (8 & 31)) & _m32;
        a = (a + m[b & mm]) & _m32;
        a = (a << (8 & 31)) & _m32;
        h[d & hm] = a;
        d = 23;
        h[d & hm] = 0;
        b = c;
        a = 0;
        a = (a << (8 & 31)) & _m32;
        a = (a + m[b & mm]) & _m32;
        b = (b + 1) & _m32;
        a = (a << (8 & 31)) & _m32;
        a = (a + m[b & mm]) & _m32;
        a >>= (5 & 31);
        a = (a << (8 & 31)) & _m32;
        h[d & hm] = a;
        z._a = a;
        z._b = b;
        z._c = c;
        z._d = d;
        z._f = f;
        return;
        z._err();
        z._err();
    }
  }
}

const List<int> _code6 = [
  18,
  104,
  135,
  255,
  88,
  114,
  69,
  175,
  223,
  143,
  65,
  175,
  255,
  231,
  26,
  47,
  10,
  95,
  0,
  70,
  151,
  20,
  133,
  1,
  112,
  63,
  3,
  95,
  0,
  52,
  95,
  0,
  74,
  70,
  25,
  59,
  112,
  95,
  2,
  52,
  95,
  3,
  52,
  95,
  3,
  74,
  70,
  25,
  59,
  9,
  112,
  25,
  59,
  9,
  112,
  25,
  59,
  9,
  112,
  25,
  59,
  9,
  112,
  25,
  59,
  9,
  112,
  25,
  59,
  9,
  112,
  25,
  59,
  9,
  59,
  112,
  95,
  11,
  70,
  151,
  24,
  133,
  1,
  112,
  95,
  12,
  52,
  66,
  175,
  1,
  60,
  74,
  9,
  68,
  60,
  95,
  12,
  74,
  70,
  25,
  59,
  112,
  95,
  14,
  52,
  66,
  167,
  3,
  60,
  74,
  9,
  9,
  68,
  60,
  95,
  14,
  74,
  70,
  25,
  59,
  112,
  95,
  16,
  52,
  66,
  175,
  3,
  60,
  74,
  9,
  9,
  9,
  68,
  60,
  95,
  16,
  74,
  70,
  25,
  59,
  112,
  95,
  19,
  52,
  74,
  4,
  207,
  8,
  132,
  207,
  8,
  112,
  95,
  21,
  52,
  74,
  4,
  207,
  8,
  132,
  9,
  207,
  8,
  132,
  215,
  5,
  207,
  8,
  112,
  56,
  0
];
@pragma('vm:unsafe:no-bounds-checks')
void _hc6(Zpaql z, int input) {
  final m = z._m, h = z._h, r = z._r;
  final mm = z._mmask, hm = z._hmask;
  var a = input & _m32, b = z._b, c = z._c, d = z._d, f = z._f;
  int x;
  var blk = 0;
  while (true) {
    switch (blk) {
      case 0:
        c = (c - 1) & _m32;
        m[c & mm] = a;
        a = (a + 255) & _m32;
        d = a;
        h[d & hm] = c;
        a = m[c & mm];
        a &= 223;
        a = (a - 65) & _m32;
        a &= 255;
        f = a < 26 ? 1 : 0;
        if (f == 0) {
          blk = 27;
          continue;
        }
        blk = 17;
        continue;
      case 17:
        d = 0;
        a = h[d & hm];
        a = (a * 20) & _m32;
        a = (a + m[c & mm]) & _m32;
        a = (a + 1) & _m32;
        h[d & hm] = a;
        blk = 30;
        continue;
        blk = 27;
        continue;
      case 27:
        d = 0;
        h[d & hm] = 0;
        blk = 30;
        continue;
      case 30:
        d = 0;
        b = c;
        a = h[d & hm];
        d = (d + 1) & _m32;
        a = ((a + m[b & mm] + 512) * 773) & _m32;
        h[d & hm] = a;
        d = 2;
        h[d & hm] = 0;
        d = 3;
        h[d & hm] = 0;
        d = 3;
        b = c;
        a = h[d & hm];
        d = (d + 1) & _m32;
        a = ((a + m[b & mm] + 512) * 773) & _m32;
        b = (b + 1) & _m32;
        h[d & hm] = a;
        d = (d + 1) & _m32;
        a = ((a + m[b & mm] + 512) * 773) & _m32;
        b = (b + 1) & _m32;
        h[d & hm] = a;
        d = (d + 1) & _m32;
        a = ((a + m[b & mm] + 512) * 773) & _m32;
        b = (b + 1) & _m32;
        h[d & hm] = a;
        d = (d + 1) & _m32;
        a = ((a + m[b & mm] + 512) * 773) & _m32;
        b = (b + 1) & _m32;
        h[d & hm] = a;
        d = (d + 1) & _m32;
        a = ((a + m[b & mm] + 512) * 773) & _m32;
        b = (b + 1) & _m32;
        h[d & hm] = a;
        d = (d + 1) & _m32;
        a = ((a + m[b & mm] + 512) * 773) & _m32;
        b = (b + 1) & _m32;
        h[d & hm] = a;
        d = (d + 1) & _m32;
        a = ((a + m[b & mm] + 512) * 773) & _m32;
        b = (b + 1) & _m32;
        a = ((a + m[b & mm] + 512) * 773) & _m32;
        h[d & hm] = a;
        d = 11;
        a = h[d & hm];
        a = (a * 24) & _m32;
        a = (a + m[c & mm]) & _m32;
        a = (a + 1) & _m32;
        h[d & hm] = a;
        d = 12;
        h[d & hm] = 0;
        a = c;
        a &= 1;
        h[d & hm] = (h[d & hm] + a + 512) * 773;
        b = c;
        b = (b + 1) & _m32;
        a = m[b & mm];
        h[d & hm] = (h[d & hm] + a + 512) * 773;
        d = 12;
        b = c;
        a = h[d & hm];
        d = (d + 1) & _m32;
        a = ((a + m[b & mm] + 512) * 773) & _m32;
        h[d & hm] = a;
        d = 14;
        h[d & hm] = 0;
        a = c;
        x = 3;
        a = x != 0 ? a % x : 0;
        h[d & hm] = (h[d & hm] + a + 512) * 773;
        b = c;
        b = (b + 1) & _m32;
        b = (b + 1) & _m32;
        a = m[b & mm];
        h[d & hm] = (h[d & hm] + a + 512) * 773;
        d = 14;
        b = c;
        a = h[d & hm];
        d = (d + 1) & _m32;
        a = ((a + m[b & mm] + 512) * 773) & _m32;
        h[d & hm] = a;
        d = 16;
        h[d & hm] = 0;
        a = c;
        a &= 3;
        h[d & hm] = (h[d & hm] + a + 512) * 773;
        b = c;
        b = (b + 1) & _m32;
        b = (b + 1) & _m32;
        b = (b + 1) & _m32;
        a = m[b & mm];
        h[d & hm] = (h[d & hm] + a + 512) * 773;
        d = 16;
        b = c;
        a = h[d & hm];
        d = (d + 1) & _m32;
        a = ((a + m[b & mm] + 512) * 773) & _m32;
        h[d & hm] = a;
        d = 19;
        h[d & hm] = 0;
        b = c;
        a = 0;
        a = (a << (8 & 31)) & _m32;
        a = (a + m[b & mm]) & _m32;
        a = (a << (8 & 31)) & _m32;
        h[d & hm] = a;
        d = 21;
        h[d & hm] = 0;
        b = c;
        a = 0;
        a = (a << (8 & 31)) & _m32;
        a = (a + m[b & mm]) & _m32;
        b = (b + 1) & _m32;
        a = (a << (8 & 31)) & _m32;
        a = (a + m[b & mm]) & _m32;
        a >>= (5 & 31);
        a = (a << (8 & 31)) & _m32;
        h[d & hm] = a;
        z._a = a;
        z._b = b;
        z._c = c;
        z._d = d;
        z._f = f;
        return;
        z._err();
        z._err();
    }
  }
}

const List<int> _code7 = [
  18,
  104,
  135,
  255,
  88,
  114,
  7,
  1,
  223,
  0,
  47,
  4,
  71,
  168,
  63,
  22,
  223,
  1,
  47,
  17,
  69,
  55,
  2,
  239,
  63,
  47,
  6,
  215,
  6,
  1,
  1,
  63,
  2,
  1,
  1,
  63,
  1,
  2,
  55,
  1,
  95,
  0,
  52,
  74,
  7,
  1,
  239,
  1,
  47,
  18,
  7,
  2,
  231,
  64,
  47,
  4,
  68,
  60,
  63,
  6,
  215,
  6,
  60,
  7,
  1,
  60,
  63,
  6,
  71,
  255,
  60,
  7,
  2,
  60,
  95,
  0,
  74,
  70,
  25,
  59,
  9,
  59,
  112,
  56,
  0
];
@pragma('vm:unsafe:no-bounds-checks')
void _hc7(Zpaql z, int input) {
  final m = z._m, h = z._h, r = z._r;
  final mm = z._mmask, hm = z._hmask;
  var a = input & _m32, b = z._b, c = z._c, d = z._d, f = z._f;
  int x;
  var blk = 0;
  while (true) {
    switch (blk) {
      case 0:
        c = (c - 1) & _m32;
        m[c & mm] = a;
        a = (a + 255) & _m32;
        d = a;
        h[d & hm] = c;
        a = r[1];
        f = a == 0 ? 1 : 0;
        if (f == 0) {
          blk = 16;
          continue;
        }
        blk = 12;
        continue;
      case 12:
        a = 168;
        blk = 38;
        continue;
        blk = 16;
        continue;
      case 16:
        f = a == 1 ? 1 : 0;
        if (f == 0) {
          blk = 37;
          continue;
        }
        blk = 20;
        continue;
      case 20:
        a = m[c & mm];
        r[2] = a;
        f = a > 63 ? 1 : 0;
        if (f == 0) {
          blk = 33;
          continue;
        }
        blk = 27;
        continue;
      case 27:
        a >>= (6 & 31);
        a = (a + 1) & _m32;
        a = (a + 1) & _m32;
        blk = 35;
        continue;
        blk = 33;
        continue;
      case 33:
        a = (a + 1) & _m32;
        a = (a + 1) & _m32;
        blk = 35;
        continue;
      case 35:
        blk = 38;
        continue;
        blk = 37;
        continue;
      case 37:
        a = (a - 1) & _m32;
        blk = 38;
        continue;
      case 38:
        r[1] = a;
        d = 0;
        h[d & hm] = 0;
        b = c;
        a = r[1];
        f = a > 1 ? 1 : 0;
        if (f == 0) {
          blk = 68;
          continue;
        }
        blk = 50;
        continue;
      case 50:
        a = r[2];
        f = a < 64 ? 1 : 0;
        if (f == 0) {
          blk = 60;
          continue;
        }
        blk = 56;
        continue;
      case 56:
        a = m[b & mm];
        h[d & hm] = (h[d & hm] + a + 512) * 773;
        blk = 66;
        continue;
        blk = 60;
        continue;
      case 60:
        a >>= (6 & 31);
        h[d & hm] = (h[d & hm] + a + 512) * 773;
        a = r[1];
        h[d & hm] = (h[d & hm] + a + 512) * 773;
        blk = 66;
        continue;
      case 66:
        blk = 74;
        continue;
        blk = 68;
        continue;
      case 68:
        a = 255;
        h[d & hm] = (h[d & hm] + a + 512) * 773;
        a = r[2];
        h[d & hm] = (h[d & hm] + a + 512) * 773;
        blk = 74;
        continue;
      case 74:
        d = 0;
        b = c;
        a = h[d & hm];
        d = (d + 1) & _m32;
        a = ((a + m[b & mm] + 512) * 773) & _m32;
        b = (b + 1) & _m32;
        a = ((a + m[b & mm] + 512) * 773) & _m32;
        h[d & hm] = a;
        z._a = a;
        z._b = b;
        z._c = c;
        z._d = d;
        z._f = f;
        return;
        z._err();
        z._err();
    }
  }
}

const List<int> _code8 = [
  18,
  104,
  135,
  255,
  88,
  114,
  7,
  1,
  223,
  0,
  47,
  4,
  71,
  168,
  63,
  22,
  223,
  1,
  47,
  17,
  69,
  55,
  2,
  239,
  63,
  47,
  6,
  215,
  6,
  1,
  1,
  63,
  2,
  1,
  1,
  63,
  1,
  2,
  55,
  1,
  95,
  0,
  52,
  74,
  7,
  1,
  239,
  1,
  47,
  18,
  7,
  2,
  231,
  64,
  47,
  4,
  68,
  60,
  63,
  6,
  215,
  6,
  60,
  7,
  1,
  60,
  63,
  6,
  71,
  255,
  60,
  7,
  2,
  60,
  56,
  0
];
@pragma('vm:unsafe:no-bounds-checks')
void _hc8(Zpaql z, int input) {
  final m = z._m, h = z._h, r = z._r;
  final mm = z._mmask, hm = z._hmask;
  var a = input & _m32, b = z._b, c = z._c, d = z._d, f = z._f;
  int x;
  var blk = 0;
  while (true) {
    switch (blk) {
      case 0:
        c = (c - 1) & _m32;
        m[c & mm] = a;
        a = (a + 255) & _m32;
        d = a;
        h[d & hm] = c;
        a = r[1];
        f = a == 0 ? 1 : 0;
        if (f == 0) {
          blk = 16;
          continue;
        }
        blk = 12;
        continue;
      case 12:
        a = 168;
        blk = 38;
        continue;
        blk = 16;
        continue;
      case 16:
        f = a == 1 ? 1 : 0;
        if (f == 0) {
          blk = 37;
          continue;
        }
        blk = 20;
        continue;
      case 20:
        a = m[c & mm];
        r[2] = a;
        f = a > 63 ? 1 : 0;
        if (f == 0) {
          blk = 33;
          continue;
        }
        blk = 27;
        continue;
      case 27:
        a >>= (6 & 31);
        a = (a + 1) & _m32;
        a = (a + 1) & _m32;
        blk = 35;
        continue;
        blk = 33;
        continue;
      case 33:
        a = (a + 1) & _m32;
        a = (a + 1) & _m32;
        blk = 35;
        continue;
      case 35:
        blk = 38;
        continue;
        blk = 37;
        continue;
      case 37:
        a = (a - 1) & _m32;
        blk = 38;
        continue;
      case 38:
        r[1] = a;
        d = 0;
        h[d & hm] = 0;
        b = c;
        a = r[1];
        f = a > 1 ? 1 : 0;
        if (f == 0) {
          blk = 68;
          continue;
        }
        blk = 50;
        continue;
      case 50:
        a = r[2];
        f = a < 64 ? 1 : 0;
        if (f == 0) {
          blk = 60;
          continue;
        }
        blk = 56;
        continue;
      case 56:
        a = m[b & mm];
        h[d & hm] = (h[d & hm] + a + 512) * 773;
        blk = 66;
        continue;
        blk = 60;
        continue;
      case 60:
        a >>= (6 & 31);
        h[d & hm] = (h[d & hm] + a + 512) * 773;
        a = r[1];
        h[d & hm] = (h[d & hm] + a + 512) * 773;
        blk = 66;
        continue;
      case 66:
        blk = 74;
        continue;
        blk = 68;
        continue;
      case 68:
        a = 255;
        h[d & hm] = (h[d & hm] + a + 512) * 773;
        a = r[2];
        h[d & hm] = (h[d & hm] + a + 512) * 773;
        blk = 74;
        continue;
      case 74:
        z._a = a;
        z._b = b;
        z._c = c;
        z._d = d;
        z._f = f;
        return;
        z._err();
        z._err();
    }
  }
}
