// Vendored from zpaq-flutter by tool/sync_zpaq.sh: do not edit here, change
// zpaq-flutter and sync again. Pure Dart port of libzpaq and zpaq 7.15 (Matt
// Mahoney, public domain) with the zpaqfranz attribute format (Franco
// Corbelli, MIT). Copyright (c) 2026 Max Brito, BSD 3-clause; see LICENSE
// for the license and the third party notices.

import 'dart:typed_data';

import 'compiler.dart';
import 'io.dart';
import 'method.dart';
import 'zpaql.dart';

/// Kinds of postprocessors generated by libzpaq's makeConfig().
enum PcompKind { lz77bits, lz77bytes, bwt, e8e9 }

/// A recognized canonical PCOMP program and its parameters.
class NativePcomp {
  final PcompKind kind;
  final bool e8;
  final int rb; // lz77bits: low offset bits
  final int minMatch; // lz77bytes
  const NativePcomp(this.kind, this.e8, {this.rb = 0, this.minMatch = 0});
}

class _Pattern {
  final Uint8List code;
  final int wildcard; // index of a free operand byte, or -1
  final NativePcomp Function(int operand) make;
  _Pattern(this.code, this.wildcard, this.make);
}

List<_Pattern>? _patterns;

Uint8List _pcompOf(String method) {
  final args = List<int>.filled(9, 0);
  final cfg = makeConfig(method, args);
  final hz = Zpaql(), pz = Zpaql();
  Compiler(cfg, args, hz, pz).compile();
  return Uint8List.fromList(pz.header.sublist(pz.hbegin, pz.hend));
}

List<_Pattern> _buildPatterns() {
  final l = <_Pattern>[];
  for (final e8 in [false, true]) {
    // Variable length LZ77: depends on rb = max(blocksize - 4, 0)
    for (var b = 4; b <= 11; ++b) {
      final rb = b - 4;
      l.add(_Pattern(_pcompOf('x$b,${e8 ? 5 : 1},4,0,3,20'), -1,
          (_) => NativePcomp(PcompKind.lz77bits, e8, rb: rb)));
    }
    // Byte aligned LZ77: the minimum match length is an operand
    final a = _pcompOf('x4,${e8 ? 6 : 2},7,0,3,20');
    final c = _pcompOf('x4,${e8 ? 6 : 2},9,0,3,20');
    var wild = -1;
    if (a.length == c.length) {
      for (var i = 0; i < a.length; ++i) {
        if (a[i] != c[i]) {
          wild = wild == -1 ? i : -2;
        }
      }
    }
    if (wild >= 0) {
      l.add(_Pattern(
          a, wild, (op) => NativePcomp(PcompKind.lz77bytes, e8, minMatch: op)));
    }
    // BWT: two traversal variants (blocks up to 16 MB, and larger)
    for (final b in [4, 5]) {
      l.add(_Pattern(_pcompOf('x$b,${e8 ? 7 : 3}'), -1,
          (_) => NativePcomp(PcompKind.bwt, e8)));
    }
  }
  l.add(_Pattern(
      _pcompOf('x4,4'), -1, (_) => const NativePcomp(PcompKind.e8e9, true)));
  return l;
}

/// Returns the native equivalent of PCOMP code [code], or null.
NativePcomp? recognizePcomp(Uint8List code, int off, int len) {
  final pats = _patterns ??= _buildPatterns();
  for (final p in pats) {
    if (p.code.length != len) continue;
    var ok = true;
    for (var i = 0; i < len; ++i) {
      if (i != p.wildcard && p.code[i] != code[off + i]) {
        ok = false;
        break;
      }
    }
    if (ok) return p.make(p.wildcard >= 0 ? code[off + p.wildcard] : 0);
  }
  return null;
}

/// Inverse of the E8E9 filter (in place), as the ZPAQL postprocessors do.
@pragma('vm:unsafe:no-bounds-checks')
void unE8e9(Uint8List buf, int n) {
  for (var i = 0; i + 4 < n; ++i) {
    if ((buf[i] & 254) == 0xe8 && ((buf[i + 4] + 1) & 254) == 0) {
      final a = (buf[i + 1] | buf[i + 2] << 8 | buf[i + 3] << 16) - i;
      buf[i + 1] = a;
      buf[i + 2] = a >> 8;
      buf[i + 3] = a >> 16;
    }
  }
}

/// Decodes one segment of postprocessor input [inp] (length [n]).
///
/// [sizeHint] is the expected output size if known (0 if not), so the output
/// buffer is allocated once at the right size.
Uint8List decodeNative(NativePcomp p, Uint8List inp, int n, int msize,
    [int sizeHint = 0]) {
  switch (p.kind) {
    case PcompKind.lz77bits:
      final out = _lz77bits(inp, n, p.rb, msize, sizeHint);
      if (p.e8) unE8e9(out.data, out.size);
      return out.bytes;
    case PcompKind.lz77bytes:
      final out = _lz77bytes(inp, n, p.minMatch, msize, sizeHint);
      if (p.e8) unE8e9(out.data, out.size);
      return out.bytes;
    case PcompKind.bwt:
      final out = _ibwt(inp, n);
      if (p.e8) unE8e9(out, out.length);
      return out;
    case PcompKind.e8e9:
      final out = Uint8List.fromList(Uint8List.sublistView(inp, 0, n));
      unE8e9(out, n);
      return out;
  }
}

class _Out {
  Uint8List data;
  int size = 0;
  _Out(int cap) : data = Uint8List(cap < 1024 ? 1024 : cap);
  _Out.of(this.data, this.size);
  Uint8List get bytes => Uint8List.sublistView(data, 0, size);
  void ensure(int k) {
    if (size + k <= data.length) return;
    var c = data.length * 2;
    while (c < size + k) {
      c *= 2;
    }
    data = Uint8List(c)..setRange(0, size, data);
  }
}

// Written without helper closures: variables captured by a closure live in
// a heap context, and this loop runs once per code of every block.
@pragma('vm:unsafe:no-bounds-checks')
_Out _lz77bits(Uint8List inp, int n, int rb, int msize, int sizeHint) {
  var d =
      Uint8List((sizeHint > 0 ? sizeHint : (n * 3 < 1024 ? 1024 : n * 3)) + 8);
  var dv = ByteData.sublistView(d);
  var size = 0;
  var pos = 0; // input byte position
  var bits = 0, nb = 0; // bit buffer, LSB first, up to 64 bits (>>> only)
  final rmask = (1 << rb) - 1;
  final bd = ByteData.sublistView(inp);
  outer:
  while (true) {
    if (nb < 32) {
      if (pos + 8 <= n) {
        bits |= bd.getUint64(pos, Endian.little) << nb;
        pos += (63 - nb) >> 3;
        nb |= 56;
      } else {
        while (nb <= 56 && pos < n) {
          bits |= inp[pos++] << nb;
          nb += 8;
        }
      }
    }
    if (nb < 2) break;
    final mm = bits & 3;
    bits >>>= 2;
    nb -= 2;
    var lo = 0;
    if (mm != 0) {
      if (nb < 3) break;
      lo = (mm - 1) * 8 + (bits & 7);
      bits >>>= 3;
      nb -= 3;
    }
    // Interleaved Elias gamma: the leading 1 is implied, each further bit
    // is preceded by a 1 and the list ends with a 0.
    var len = 1;
    while (true) {
      if (nb < 2) {
        if (pos + 8 <= n) {
          // One 64 bit load: the bytes past the ones counted are loaded
          // again next time, the same bits, so ORing them is harmless.
          bits |= bd.getUint64(pos, Endian.little) << nb;
          pos += (63 - nb) >> 3;
          nb |= 56;
        } else {
          while (nb <= 56 && pos < n) {
            bits |= inp[pos++] << nb;
            nb += 8;
          }
        }
        if (nb < 1) break outer;
      }
      if ((bits & 1) == 0) {
        bits >>>= 1;
        nb -= 1;
        break;
      }
      if (nb < 2) break outer;
      len = len * 2 + ((bits >>> 1) & 1);
      bits >>>= 2;
      nb -= 2;
    }
    if (mm == 0) {
      // literal run
      if (size + len > d.length) {
        var c = d.length * 2;
        while (c < size + len) {
          c *= 2;
        }
        d = Uint8List(c)..setRange(0, size, d);
        dv = ByteData.sublistView(d);
      }
      for (var i = 0; i < len; ++i) {
        if (nb < 8) {
          while (nb <= 56 && pos < n) {
            bits |= inp[pos++] << nb;
            nb += 8;
          }
          if (nb < 8) break outer;
        }
        d[size++] = bits & 255;
        bits >>>= 8;
        nb -= 8;
      }
    } else {
      if (nb < 32) {
        if (pos + 8 <= n) {
          // One 64 bit load: the bytes past the ones counted are loaded
          // again next time, the same bits, so ORing them is harmless.
          bits |= bd.getUint64(pos, Endian.little) << nb;
          pos += (63 - nb) >> 3;
          nb |= 56;
        } else {
          while (nb <= 56 && pos < n) {
            bits |= inp[pos++] << nb;
            nb += 8;
          }
        }
      }
      if (nb < 2 + rb) break;
      len = len * 4 + (bits & 3);
      bits >>>= 2;
      nb -= 2;
      final r = bits & rmask;
      bits >>>= rb;
      nb -= rb;
      if (nb < lo) {
        if (pos + 8 <= n) {
          // One 64 bit load: the bytes past the ones counted are loaded
          // again next time, the same bits, so ORing them is harmless.
          bits |= bd.getUint64(pos, Endian.little) << nb;
          pos += (63 - nb) >> 3;
          nb |= 56;
        } else {
          while (nb <= 56 && pos < n) {
            bits |= inp[pos++] << nb;
            nb += 8;
          }
        }
        if (nb < lo) break;
      }
      final q = bits & ((1 << lo) - 1);
      bits >>>= lo;
      nb -= lo;
      final off = (((1 << lo) | q) << rb) + r - rmask;
      if (off <= 0 || off > size) {
        zpaqError('LZ77 offset out of range');
      }
      // 8 bytes of slack: the word copy below may write past the match
      if (size + len + 8 > d.length) {
        var c = d.length * 2;
        while (c < size + len + 8) {
          c *= 2;
        }
        d = Uint8List(c)..setRange(0, size, d);
        dv = ByteData.sublistView(d);
      }
      var src = size - off;
      if (off >= 8 && (len <= 64 || off < len)) {
        // Short matches: 8 bytes at a time (setRange is a rep movsb, slow
        // to start). With off >= 8 every word read is already final, even
        // when the match overlaps itself; bytes written past the end are
        // overwritten later.
        for (var k = 0; k < len; k += 8) {
          dv.setUint64(
              size + k, dv.getUint64(src + k, Endian.little), Endian.little);
        }
        size += len;
      } else if (off >= len) {
        d.setRange(size, size + len, d, src);
        size += len;
      } else {
        // overlapping copy repeats the last off bytes
        for (var k = 0; k < len; ++k) {
          d[size++] = d[src++];
        }
      }
    }
  }
  if (size > msize) zpaqError('LZ77 output larger than buffer');
  return _Out.of(d, size);
}

@pragma('vm:unsafe:no-bounds-checks')
_Out _lz77bytes(Uint8List inp, int n, int minMatch, int msize, int sizeHint) {
  final out = _Out(sizeHint > 0 ? sizeHint : n * 3);
  final iv = ByteData.sublistView(inp);
  var d = out.data;
  var dv = ByteData.sublistView(d);
  var i = 0;
  // Copies are 8 bytes at a time (setRange is a rep movsb, slow to start
  // on these short runs), so the output keeps 8 bytes of slack; bytes
  // written past the end are overwritten later.
  while (i < n) {
    final c = inp[i++];
    final yy = c >> 6;
    if (yy == 0) {
      final len = (c & 63) + 1;
      if (i + len > n) break;
      out.ensure(len + 8);
      if (!identical(out.data, d)) {
        d = out.data;
        dv = ByteData.sublistView(d);
      }
      final t = out.size;
      if (i + len + 8 <= n) {
        for (var k = 0; k < len; k += 8) {
          dv.setUint64(
              t + k, iv.getUint64(i + k, Endian.little), Endian.little);
        }
      } else {
        d.setRange(t, t + len, inp, i);
      }
      out.size = t + len;
      i += len;
    } else {
      final len = (c & 63) + minMatch;
      if (i + yy + 1 > n) break;
      var off = 0;
      for (var k = 0; k <= yy; ++k) {
        off = (off << 8) | inp[i++];
      }
      off += 1;
      if (off > out.size) zpaqError('LZ77 offset out of range');
      out.ensure(len + 8);
      if (!identical(out.data, d)) {
        d = out.data;
        dv = ByteData.sublistView(d);
      }
      var s = out.size - off;
      var t = out.size;
      if (off >= 8) {
        // every word read is already final, even when the match overlaps
        for (var k = 0; k < len; k += 8) {
          dv.setUint64(
              t + k, dv.getUint64(s + k, Endian.little), Endian.little);
        }
        t += len;
      } else {
        for (var k = 0; k < len; ++k) {
          d[t++] = d[s++];
        }
      }
      out.size = t;
    }
  }
  if (out.size > msize) zpaqError('LZ77 output larger than buffer');
  return out;
}

/// Inverse BWT of libzpaq's format: n-4 BWT bytes (with a 255 at the
/// sentinel position) followed by the 4 byte LSB first sentinel index.
@pragma('vm:unsafe:no-bounds-checks')
Uint8List _ibwt(Uint8List inp, int n) {
  if (n < 4) zpaqError('BWT block too small');
  final m = n - 4; // BWT length including the sentinel
  final idx = inp[m] | inp[m + 1] << 8 | inp[m + 2] << 16 | inp[m + 3] << 24;
  if (m == 0) return Uint8List(0);
  if (idx < 0 || idx >= m) zpaqError('bad BWT index');
  // count[c] = occurrences of byte c, excluding the sentinel
  final start = Int32List(257);
  for (var i = 0; i < m; ++i) {
    if (i != idx) start[inp[i] + 1]++;
  }
  // start[c] = first row whose first symbol is c (row 0 is the sentinel)
  start[0] = 1;
  for (var c = 1; c <= 256; ++c) {
    start[c] += start[c - 1];
  }
  // next[row of F] = row in L of the same occurrence (forward traversal)
  final next = Int32List(m);
  final pos = Int32List(256);
  for (var c = 0; c < 256; ++c) {
    pos[c] = start[c];
  }
  next[0] = idx; // the sentinel in F is the sentinel in L
  for (var i = 0; i < m; ++i) {
    if (i == idx) continue;
    next[pos[inp[i]]++] = i;
  }
  // Row 0 is "$T": its successor in text order is found through next.
  // F column: first symbol of each row
  final f = Uint8List(m);
  for (var c = 0; c < 256; ++c) {
    f.fillRange(start[c], start[c + 1], c);
  }
  final out = Uint8List(m - 1);
  var r = next[0];
  for (var k = 0; k < m - 1; ++k) {
    out[k] = f[r];
    r = next[r];
  }
  return out;
}
