// Vendored from zpaq-flutter by tool/sync_zpaq.sh: do not edit here, change
// zpaq-flutter and sync again. Pure Dart port of libzpaq and zpaq 7.15 (Matt
// Mahoney, public domain) with the zpaqfranz attribute format (Franco
// Corbelli, MIT). Copyright (c) 2026 Max Brito, BSD 3-clause; see LICENSE
// for the license and the third party notices.

import 'dart:typed_data';

/// Incremental SHA-1, as used by ZPAQ for fragment and segment checksums.
class Sha1 {
  final Uint32List _h = Uint32List(5);
  final Uint32List _w = Uint32List(16);
  final Uint8List _buf = Uint8List(64);
  int _bufLen = 0;
  int _len = 0; // total bytes

  Sha1() {
    reset();
  }

  /// Number of bytes hashed since the last reset.
  int get length => _len;

  void reset() {
    _h[0] = 0x67452301;
    _h[1] = 0xEFCDAB89;
    _h[2] = 0x98BADCFE;
    _h[3] = 0x10325476;
    _h[4] = 0xC3D2E1F0;
    _bufLen = 0;
    _len = 0;
  }

  void addByte(int c) {
    _buf[_bufLen++] = c;
    _len++;
    if (_bufLen == 64) {
      _process(_buf, 0);
      _bufLen = 0;
    }
  }

  void add(List<int> data, [int start = 0, int? end]) {
    end ??= data.length;
    var i = start;
    _len += end - start;
    if (_bufLen > 0) {
      while (i < end && _bufLen < 64) {
        _buf[_bufLen++] = data[i++];
      }
      if (_bufLen == 64) {
        _process(_buf, 0);
        _bufLen = 0;
      }
    }
    if (data is Uint8List) {
      while (end - i >= 64) {
        _process(data, i);
        i += 64;
      }
    } else {
      while (end - i >= 64) {
        _buf.setRange(0, 64, data, i);
        _process(_buf, 0);
        i += 64;
      }
    }
    while (i < end) {
      _buf[_bufLen++] = data[i++];
    }
  }

  /// Returns the 20 byte digest and resets the state.
  Uint8List digest() {
    final bits = _len * 8;
    _buf[_bufLen++] = 0x80;
    if (_bufLen > 56) {
      while (_bufLen < 64) {
        _buf[_bufLen++] = 0;
      }
      _process(_buf, 0);
      _bufLen = 0;
    }
    while (_bufLen < 56) {
      _buf[_bufLen++] = 0;
    }
    for (var i = 7; i >= 0; --i) {
      _buf[_bufLen++] = (bits >> (i * 8)) & 255;
    }
    _process(_buf, 0);
    final out = Uint8List(20);
    for (var i = 0; i < 5; ++i) {
      out[4 * i] = _h[i] >> 24;
      out[4 * i + 1] = _h[i] >> 16;
      out[4 * i + 2] = _h[i] >> 8;
      out[4 * i + 3] = _h[i];
    }
    reset();
    return out;
  }

  static Uint8List hash(List<int> data, [int start = 0, int? end]) =>
      (Sha1()..add(data, start, end)).digest();

  // GENERATED by tool/gen_sha1.py from here to the end of the file.
  @pragma('vm:unsafe:no-bounds-checks')
  void _process(Uint8List p, int o) {
    final w = _w, h = _h;
    for (var i = 0; i < 16; ++i) {
      w[i] = p[o] << 24 | p[o + 1] << 16 | p[o + 2] << 8 | p[o + 3];
      o += 4;
    }
    var a = h[0], b = h[1], c = h[2], d = h[3], e = h[4];
    e = (e + 0x5A827999 + w[0] + (d ^ (b & (c ^ d))) + ((a << 5) | (a >> 27))) &
        0xFFFFFFFF;
    b = ((b << 30) | (b >> 2)) & 0xFFFFFFFF;
    d = (d + 0x5A827999 + w[1] + (c ^ (a & (b ^ c))) + ((e << 5) | (e >> 27))) &
        0xFFFFFFFF;
    a = ((a << 30) | (a >> 2)) & 0xFFFFFFFF;
    c = (c + 0x5A827999 + w[2] + (b ^ (e & (a ^ b))) + ((d << 5) | (d >> 27))) &
        0xFFFFFFFF;
    e = ((e << 30) | (e >> 2)) & 0xFFFFFFFF;
    b = (b + 0x5A827999 + w[3] + (a ^ (d & (e ^ a))) + ((c << 5) | (c >> 27))) &
        0xFFFFFFFF;
    d = ((d << 30) | (d >> 2)) & 0xFFFFFFFF;
    a = (a + 0x5A827999 + w[4] + (e ^ (c & (d ^ e))) + ((b << 5) | (b >> 27))) &
        0xFFFFFFFF;
    c = ((c << 30) | (c >> 2)) & 0xFFFFFFFF;
    e = (e + 0x5A827999 + w[5] + (d ^ (b & (c ^ d))) + ((a << 5) | (a >> 27))) &
        0xFFFFFFFF;
    b = ((b << 30) | (b >> 2)) & 0xFFFFFFFF;
    d = (d + 0x5A827999 + w[6] + (c ^ (a & (b ^ c))) + ((e << 5) | (e >> 27))) &
        0xFFFFFFFF;
    a = ((a << 30) | (a >> 2)) & 0xFFFFFFFF;
    c = (c + 0x5A827999 + w[7] + (b ^ (e & (a ^ b))) + ((d << 5) | (d >> 27))) &
        0xFFFFFFFF;
    e = ((e << 30) | (e >> 2)) & 0xFFFFFFFF;
    b = (b + 0x5A827999 + w[8] + (a ^ (d & (e ^ a))) + ((c << 5) | (c >> 27))) &
        0xFFFFFFFF;
    d = ((d << 30) | (d >> 2)) & 0xFFFFFFFF;
    a = (a + 0x5A827999 + w[9] + (e ^ (c & (d ^ e))) + ((b << 5) | (b >> 27))) &
        0xFFFFFFFF;
    c = ((c << 30) | (c >> 2)) & 0xFFFFFFFF;
    e = (e +
            0x5A827999 +
            w[10] +
            (d ^ (b & (c ^ d))) +
            ((a << 5) | (a >> 27))) &
        0xFFFFFFFF;
    b = ((b << 30) | (b >> 2)) & 0xFFFFFFFF;
    d = (d +
            0x5A827999 +
            w[11] +
            (c ^ (a & (b ^ c))) +
            ((e << 5) | (e >> 27))) &
        0xFFFFFFFF;
    a = ((a << 30) | (a >> 2)) & 0xFFFFFFFF;
    c = (c +
            0x5A827999 +
            w[12] +
            (b ^ (e & (a ^ b))) +
            ((d << 5) | (d >> 27))) &
        0xFFFFFFFF;
    e = ((e << 30) | (e >> 2)) & 0xFFFFFFFF;
    b = (b +
            0x5A827999 +
            w[13] +
            (a ^ (d & (e ^ a))) +
            ((c << 5) | (c >> 27))) &
        0xFFFFFFFF;
    d = ((d << 30) | (d >> 2)) & 0xFFFFFFFF;
    a = (a +
            0x5A827999 +
            w[14] +
            (e ^ (c & (d ^ e))) +
            ((b << 5) | (b >> 27))) &
        0xFFFFFFFF;
    c = ((c << 30) | (c >> 2)) & 0xFFFFFFFF;
    e = (e +
            0x5A827999 +
            w[15] +
            (d ^ (b & (c ^ d))) +
            ((a << 5) | (a >> 27))) &
        0xFFFFFFFF;
    b = ((b << 30) | (b >> 2)) & 0xFFFFFFFF;
    final x16 = w[13] ^ w[8] ^ w[2] ^ w[0];
    w[0] = ((x16 << 1) | (x16 >> 31)) & 0xFFFFFFFF;
    d = (d + 0x5A827999 + w[0] + (c ^ (a & (b ^ c))) + ((e << 5) | (e >> 27))) &
        0xFFFFFFFF;
    a = ((a << 30) | (a >> 2)) & 0xFFFFFFFF;
    final x17 = w[14] ^ w[9] ^ w[3] ^ w[1];
    w[1] = ((x17 << 1) | (x17 >> 31)) & 0xFFFFFFFF;
    c = (c + 0x5A827999 + w[1] + (b ^ (e & (a ^ b))) + ((d << 5) | (d >> 27))) &
        0xFFFFFFFF;
    e = ((e << 30) | (e >> 2)) & 0xFFFFFFFF;
    final x18 = w[15] ^ w[10] ^ w[4] ^ w[2];
    w[2] = ((x18 << 1) | (x18 >> 31)) & 0xFFFFFFFF;
    b = (b + 0x5A827999 + w[2] + (a ^ (d & (e ^ a))) + ((c << 5) | (c >> 27))) &
        0xFFFFFFFF;
    d = ((d << 30) | (d >> 2)) & 0xFFFFFFFF;
    final x19 = w[0] ^ w[11] ^ w[5] ^ w[3];
    w[3] = ((x19 << 1) | (x19 >> 31)) & 0xFFFFFFFF;
    a = (a + 0x5A827999 + w[3] + (e ^ (c & (d ^ e))) + ((b << 5) | (b >> 27))) &
        0xFFFFFFFF;
    c = ((c << 30) | (c >> 2)) & 0xFFFFFFFF;
    final x20 = w[1] ^ w[12] ^ w[6] ^ w[4];
    w[4] = ((x20 << 1) | (x20 >> 31)) & 0xFFFFFFFF;
    e = (e + 0x6ED9EBA1 + w[4] + (b ^ c ^ d) + ((a << 5) | (a >> 27))) &
        0xFFFFFFFF;
    b = ((b << 30) | (b >> 2)) & 0xFFFFFFFF;
    final x21 = w[2] ^ w[13] ^ w[7] ^ w[5];
    w[5] = ((x21 << 1) | (x21 >> 31)) & 0xFFFFFFFF;
    d = (d + 0x6ED9EBA1 + w[5] + (a ^ b ^ c) + ((e << 5) | (e >> 27))) &
        0xFFFFFFFF;
    a = ((a << 30) | (a >> 2)) & 0xFFFFFFFF;
    final x22 = w[3] ^ w[14] ^ w[8] ^ w[6];
    w[6] = ((x22 << 1) | (x22 >> 31)) & 0xFFFFFFFF;
    c = (c + 0x6ED9EBA1 + w[6] + (e ^ a ^ b) + ((d << 5) | (d >> 27))) &
        0xFFFFFFFF;
    e = ((e << 30) | (e >> 2)) & 0xFFFFFFFF;
    final x23 = w[4] ^ w[15] ^ w[9] ^ w[7];
    w[7] = ((x23 << 1) | (x23 >> 31)) & 0xFFFFFFFF;
    b = (b + 0x6ED9EBA1 + w[7] + (d ^ e ^ a) + ((c << 5) | (c >> 27))) &
        0xFFFFFFFF;
    d = ((d << 30) | (d >> 2)) & 0xFFFFFFFF;
    final x24 = w[5] ^ w[0] ^ w[10] ^ w[8];
    w[8] = ((x24 << 1) | (x24 >> 31)) & 0xFFFFFFFF;
    a = (a + 0x6ED9EBA1 + w[8] + (c ^ d ^ e) + ((b << 5) | (b >> 27))) &
        0xFFFFFFFF;
    c = ((c << 30) | (c >> 2)) & 0xFFFFFFFF;
    final x25 = w[6] ^ w[1] ^ w[11] ^ w[9];
    w[9] = ((x25 << 1) | (x25 >> 31)) & 0xFFFFFFFF;
    e = (e + 0x6ED9EBA1 + w[9] + (b ^ c ^ d) + ((a << 5) | (a >> 27))) &
        0xFFFFFFFF;
    b = ((b << 30) | (b >> 2)) & 0xFFFFFFFF;
    final x26 = w[7] ^ w[2] ^ w[12] ^ w[10];
    w[10] = ((x26 << 1) | (x26 >> 31)) & 0xFFFFFFFF;
    d = (d + 0x6ED9EBA1 + w[10] + (a ^ b ^ c) + ((e << 5) | (e >> 27))) &
        0xFFFFFFFF;
    a = ((a << 30) | (a >> 2)) & 0xFFFFFFFF;
    final x27 = w[8] ^ w[3] ^ w[13] ^ w[11];
    w[11] = ((x27 << 1) | (x27 >> 31)) & 0xFFFFFFFF;
    c = (c + 0x6ED9EBA1 + w[11] + (e ^ a ^ b) + ((d << 5) | (d >> 27))) &
        0xFFFFFFFF;
    e = ((e << 30) | (e >> 2)) & 0xFFFFFFFF;
    final x28 = w[9] ^ w[4] ^ w[14] ^ w[12];
    w[12] = ((x28 << 1) | (x28 >> 31)) & 0xFFFFFFFF;
    b = (b + 0x6ED9EBA1 + w[12] + (d ^ e ^ a) + ((c << 5) | (c >> 27))) &
        0xFFFFFFFF;
    d = ((d << 30) | (d >> 2)) & 0xFFFFFFFF;
    final x29 = w[10] ^ w[5] ^ w[15] ^ w[13];
    w[13] = ((x29 << 1) | (x29 >> 31)) & 0xFFFFFFFF;
    a = (a + 0x6ED9EBA1 + w[13] + (c ^ d ^ e) + ((b << 5) | (b >> 27))) &
        0xFFFFFFFF;
    c = ((c << 30) | (c >> 2)) & 0xFFFFFFFF;
    final x30 = w[11] ^ w[6] ^ w[0] ^ w[14];
    w[14] = ((x30 << 1) | (x30 >> 31)) & 0xFFFFFFFF;
    e = (e + 0x6ED9EBA1 + w[14] + (b ^ c ^ d) + ((a << 5) | (a >> 27))) &
        0xFFFFFFFF;
    b = ((b << 30) | (b >> 2)) & 0xFFFFFFFF;
    final x31 = w[12] ^ w[7] ^ w[1] ^ w[15];
    w[15] = ((x31 << 1) | (x31 >> 31)) & 0xFFFFFFFF;
    d = (d + 0x6ED9EBA1 + w[15] + (a ^ b ^ c) + ((e << 5) | (e >> 27))) &
        0xFFFFFFFF;
    a = ((a << 30) | (a >> 2)) & 0xFFFFFFFF;
    final x32 = w[13] ^ w[8] ^ w[2] ^ w[0];
    w[0] = ((x32 << 1) | (x32 >> 31)) & 0xFFFFFFFF;
    c = (c + 0x6ED9EBA1 + w[0] + (e ^ a ^ b) + ((d << 5) | (d >> 27))) &
        0xFFFFFFFF;
    e = ((e << 30) | (e >> 2)) & 0xFFFFFFFF;
    final x33 = w[14] ^ w[9] ^ w[3] ^ w[1];
    w[1] = ((x33 << 1) | (x33 >> 31)) & 0xFFFFFFFF;
    b = (b + 0x6ED9EBA1 + w[1] + (d ^ e ^ a) + ((c << 5) | (c >> 27))) &
        0xFFFFFFFF;
    d = ((d << 30) | (d >> 2)) & 0xFFFFFFFF;
    final x34 = w[15] ^ w[10] ^ w[4] ^ w[2];
    w[2] = ((x34 << 1) | (x34 >> 31)) & 0xFFFFFFFF;
    a = (a + 0x6ED9EBA1 + w[2] + (c ^ d ^ e) + ((b << 5) | (b >> 27))) &
        0xFFFFFFFF;
    c = ((c << 30) | (c >> 2)) & 0xFFFFFFFF;
    final x35 = w[0] ^ w[11] ^ w[5] ^ w[3];
    w[3] = ((x35 << 1) | (x35 >> 31)) & 0xFFFFFFFF;
    e = (e + 0x6ED9EBA1 + w[3] + (b ^ c ^ d) + ((a << 5) | (a >> 27))) &
        0xFFFFFFFF;
    b = ((b << 30) | (b >> 2)) & 0xFFFFFFFF;
    final x36 = w[1] ^ w[12] ^ w[6] ^ w[4];
    w[4] = ((x36 << 1) | (x36 >> 31)) & 0xFFFFFFFF;
    d = (d + 0x6ED9EBA1 + w[4] + (a ^ b ^ c) + ((e << 5) | (e >> 27))) &
        0xFFFFFFFF;
    a = ((a << 30) | (a >> 2)) & 0xFFFFFFFF;
    final x37 = w[2] ^ w[13] ^ w[7] ^ w[5];
    w[5] = ((x37 << 1) | (x37 >> 31)) & 0xFFFFFFFF;
    c = (c + 0x6ED9EBA1 + w[5] + (e ^ a ^ b) + ((d << 5) | (d >> 27))) &
        0xFFFFFFFF;
    e = ((e << 30) | (e >> 2)) & 0xFFFFFFFF;
    final x38 = w[3] ^ w[14] ^ w[8] ^ w[6];
    w[6] = ((x38 << 1) | (x38 >> 31)) & 0xFFFFFFFF;
    b = (b + 0x6ED9EBA1 + w[6] + (d ^ e ^ a) + ((c << 5) | (c >> 27))) &
        0xFFFFFFFF;
    d = ((d << 30) | (d >> 2)) & 0xFFFFFFFF;
    final x39 = w[4] ^ w[15] ^ w[9] ^ w[7];
    w[7] = ((x39 << 1) | (x39 >> 31)) & 0xFFFFFFFF;
    a = (a + 0x6ED9EBA1 + w[7] + (c ^ d ^ e) + ((b << 5) | (b >> 27))) &
        0xFFFFFFFF;
    c = ((c << 30) | (c >> 2)) & 0xFFFFFFFF;
    final x40 = w[5] ^ w[0] ^ w[10] ^ w[8];
    w[8] = ((x40 << 1) | (x40 >> 31)) & 0xFFFFFFFF;
    e = (e +
            0x8F1BBCDC +
            w[8] +
            ((b & c) | ((b | c) & d)) +
            ((a << 5) | (a >> 27))) &
        0xFFFFFFFF;
    b = ((b << 30) | (b >> 2)) & 0xFFFFFFFF;
    final x41 = w[6] ^ w[1] ^ w[11] ^ w[9];
    w[9] = ((x41 << 1) | (x41 >> 31)) & 0xFFFFFFFF;
    d = (d +
            0x8F1BBCDC +
            w[9] +
            ((a & b) | ((a | b) & c)) +
            ((e << 5) | (e >> 27))) &
        0xFFFFFFFF;
    a = ((a << 30) | (a >> 2)) & 0xFFFFFFFF;
    final x42 = w[7] ^ w[2] ^ w[12] ^ w[10];
    w[10] = ((x42 << 1) | (x42 >> 31)) & 0xFFFFFFFF;
    c = (c +
            0x8F1BBCDC +
            w[10] +
            ((e & a) | ((e | a) & b)) +
            ((d << 5) | (d >> 27))) &
        0xFFFFFFFF;
    e = ((e << 30) | (e >> 2)) & 0xFFFFFFFF;
    final x43 = w[8] ^ w[3] ^ w[13] ^ w[11];
    w[11] = ((x43 << 1) | (x43 >> 31)) & 0xFFFFFFFF;
    b = (b +
            0x8F1BBCDC +
            w[11] +
            ((d & e) | ((d | e) & a)) +
            ((c << 5) | (c >> 27))) &
        0xFFFFFFFF;
    d = ((d << 30) | (d >> 2)) & 0xFFFFFFFF;
    final x44 = w[9] ^ w[4] ^ w[14] ^ w[12];
    w[12] = ((x44 << 1) | (x44 >> 31)) & 0xFFFFFFFF;
    a = (a +
            0x8F1BBCDC +
            w[12] +
            ((c & d) | ((c | d) & e)) +
            ((b << 5) | (b >> 27))) &
        0xFFFFFFFF;
    c = ((c << 30) | (c >> 2)) & 0xFFFFFFFF;
    final x45 = w[10] ^ w[5] ^ w[15] ^ w[13];
    w[13] = ((x45 << 1) | (x45 >> 31)) & 0xFFFFFFFF;
    e = (e +
            0x8F1BBCDC +
            w[13] +
            ((b & c) | ((b | c) & d)) +
            ((a << 5) | (a >> 27))) &
        0xFFFFFFFF;
    b = ((b << 30) | (b >> 2)) & 0xFFFFFFFF;
    final x46 = w[11] ^ w[6] ^ w[0] ^ w[14];
    w[14] = ((x46 << 1) | (x46 >> 31)) & 0xFFFFFFFF;
    d = (d +
            0x8F1BBCDC +
            w[14] +
            ((a & b) | ((a | b) & c)) +
            ((e << 5) | (e >> 27))) &
        0xFFFFFFFF;
    a = ((a << 30) | (a >> 2)) & 0xFFFFFFFF;
    final x47 = w[12] ^ w[7] ^ w[1] ^ w[15];
    w[15] = ((x47 << 1) | (x47 >> 31)) & 0xFFFFFFFF;
    c = (c +
            0x8F1BBCDC +
            w[15] +
            ((e & a) | ((e | a) & b)) +
            ((d << 5) | (d >> 27))) &
        0xFFFFFFFF;
    e = ((e << 30) | (e >> 2)) & 0xFFFFFFFF;
    final x48 = w[13] ^ w[8] ^ w[2] ^ w[0];
    w[0] = ((x48 << 1) | (x48 >> 31)) & 0xFFFFFFFF;
    b = (b +
            0x8F1BBCDC +
            w[0] +
            ((d & e) | ((d | e) & a)) +
            ((c << 5) | (c >> 27))) &
        0xFFFFFFFF;
    d = ((d << 30) | (d >> 2)) & 0xFFFFFFFF;
    final x49 = w[14] ^ w[9] ^ w[3] ^ w[1];
    w[1] = ((x49 << 1) | (x49 >> 31)) & 0xFFFFFFFF;
    a = (a +
            0x8F1BBCDC +
            w[1] +
            ((c & d) | ((c | d) & e)) +
            ((b << 5) | (b >> 27))) &
        0xFFFFFFFF;
    c = ((c << 30) | (c >> 2)) & 0xFFFFFFFF;
    final x50 = w[15] ^ w[10] ^ w[4] ^ w[2];
    w[2] = ((x50 << 1) | (x50 >> 31)) & 0xFFFFFFFF;
    e = (e +
            0x8F1BBCDC +
            w[2] +
            ((b & c) | ((b | c) & d)) +
            ((a << 5) | (a >> 27))) &
        0xFFFFFFFF;
    b = ((b << 30) | (b >> 2)) & 0xFFFFFFFF;
    final x51 = w[0] ^ w[11] ^ w[5] ^ w[3];
    w[3] = ((x51 << 1) | (x51 >> 31)) & 0xFFFFFFFF;
    d = (d +
            0x8F1BBCDC +
            w[3] +
            ((a & b) | ((a | b) & c)) +
            ((e << 5) | (e >> 27))) &
        0xFFFFFFFF;
    a = ((a << 30) | (a >> 2)) & 0xFFFFFFFF;
    final x52 = w[1] ^ w[12] ^ w[6] ^ w[4];
    w[4] = ((x52 << 1) | (x52 >> 31)) & 0xFFFFFFFF;
    c = (c +
            0x8F1BBCDC +
            w[4] +
            ((e & a) | ((e | a) & b)) +
            ((d << 5) | (d >> 27))) &
        0xFFFFFFFF;
    e = ((e << 30) | (e >> 2)) & 0xFFFFFFFF;
    final x53 = w[2] ^ w[13] ^ w[7] ^ w[5];
    w[5] = ((x53 << 1) | (x53 >> 31)) & 0xFFFFFFFF;
    b = (b +
            0x8F1BBCDC +
            w[5] +
            ((d & e) | ((d | e) & a)) +
            ((c << 5) | (c >> 27))) &
        0xFFFFFFFF;
    d = ((d << 30) | (d >> 2)) & 0xFFFFFFFF;
    final x54 = w[3] ^ w[14] ^ w[8] ^ w[6];
    w[6] = ((x54 << 1) | (x54 >> 31)) & 0xFFFFFFFF;
    a = (a +
            0x8F1BBCDC +
            w[6] +
            ((c & d) | ((c | d) & e)) +
            ((b << 5) | (b >> 27))) &
        0xFFFFFFFF;
    c = ((c << 30) | (c >> 2)) & 0xFFFFFFFF;
    final x55 = w[4] ^ w[15] ^ w[9] ^ w[7];
    w[7] = ((x55 << 1) | (x55 >> 31)) & 0xFFFFFFFF;
    e = (e +
            0x8F1BBCDC +
            w[7] +
            ((b & c) | ((b | c) & d)) +
            ((a << 5) | (a >> 27))) &
        0xFFFFFFFF;
    b = ((b << 30) | (b >> 2)) & 0xFFFFFFFF;
    final x56 = w[5] ^ w[0] ^ w[10] ^ w[8];
    w[8] = ((x56 << 1) | (x56 >> 31)) & 0xFFFFFFFF;
    d = (d +
            0x8F1BBCDC +
            w[8] +
            ((a & b) | ((a | b) & c)) +
            ((e << 5) | (e >> 27))) &
        0xFFFFFFFF;
    a = ((a << 30) | (a >> 2)) & 0xFFFFFFFF;
    final x57 = w[6] ^ w[1] ^ w[11] ^ w[9];
    w[9] = ((x57 << 1) | (x57 >> 31)) & 0xFFFFFFFF;
    c = (c +
            0x8F1BBCDC +
            w[9] +
            ((e & a) | ((e | a) & b)) +
            ((d << 5) | (d >> 27))) &
        0xFFFFFFFF;
    e = ((e << 30) | (e >> 2)) & 0xFFFFFFFF;
    final x58 = w[7] ^ w[2] ^ w[12] ^ w[10];
    w[10] = ((x58 << 1) | (x58 >> 31)) & 0xFFFFFFFF;
    b = (b +
            0x8F1BBCDC +
            w[10] +
            ((d & e) | ((d | e) & a)) +
            ((c << 5) | (c >> 27))) &
        0xFFFFFFFF;
    d = ((d << 30) | (d >> 2)) & 0xFFFFFFFF;
    final x59 = w[8] ^ w[3] ^ w[13] ^ w[11];
    w[11] = ((x59 << 1) | (x59 >> 31)) & 0xFFFFFFFF;
    a = (a +
            0x8F1BBCDC +
            w[11] +
            ((c & d) | ((c | d) & e)) +
            ((b << 5) | (b >> 27))) &
        0xFFFFFFFF;
    c = ((c << 30) | (c >> 2)) & 0xFFFFFFFF;
    final x60 = w[9] ^ w[4] ^ w[14] ^ w[12];
    w[12] = ((x60 << 1) | (x60 >> 31)) & 0xFFFFFFFF;
    e = (e + 0xCA62C1D6 + w[12] + (b ^ c ^ d) + ((a << 5) | (a >> 27))) &
        0xFFFFFFFF;
    b = ((b << 30) | (b >> 2)) & 0xFFFFFFFF;
    final x61 = w[10] ^ w[5] ^ w[15] ^ w[13];
    w[13] = ((x61 << 1) | (x61 >> 31)) & 0xFFFFFFFF;
    d = (d + 0xCA62C1D6 + w[13] + (a ^ b ^ c) + ((e << 5) | (e >> 27))) &
        0xFFFFFFFF;
    a = ((a << 30) | (a >> 2)) & 0xFFFFFFFF;
    final x62 = w[11] ^ w[6] ^ w[0] ^ w[14];
    w[14] = ((x62 << 1) | (x62 >> 31)) & 0xFFFFFFFF;
    c = (c + 0xCA62C1D6 + w[14] + (e ^ a ^ b) + ((d << 5) | (d >> 27))) &
        0xFFFFFFFF;
    e = ((e << 30) | (e >> 2)) & 0xFFFFFFFF;
    final x63 = w[12] ^ w[7] ^ w[1] ^ w[15];
    w[15] = ((x63 << 1) | (x63 >> 31)) & 0xFFFFFFFF;
    b = (b + 0xCA62C1D6 + w[15] + (d ^ e ^ a) + ((c << 5) | (c >> 27))) &
        0xFFFFFFFF;
    d = ((d << 30) | (d >> 2)) & 0xFFFFFFFF;
    final x64 = w[13] ^ w[8] ^ w[2] ^ w[0];
    w[0] = ((x64 << 1) | (x64 >> 31)) & 0xFFFFFFFF;
    a = (a + 0xCA62C1D6 + w[0] + (c ^ d ^ e) + ((b << 5) | (b >> 27))) &
        0xFFFFFFFF;
    c = ((c << 30) | (c >> 2)) & 0xFFFFFFFF;
    final x65 = w[14] ^ w[9] ^ w[3] ^ w[1];
    w[1] = ((x65 << 1) | (x65 >> 31)) & 0xFFFFFFFF;
    e = (e + 0xCA62C1D6 + w[1] + (b ^ c ^ d) + ((a << 5) | (a >> 27))) &
        0xFFFFFFFF;
    b = ((b << 30) | (b >> 2)) & 0xFFFFFFFF;
    final x66 = w[15] ^ w[10] ^ w[4] ^ w[2];
    w[2] = ((x66 << 1) | (x66 >> 31)) & 0xFFFFFFFF;
    d = (d + 0xCA62C1D6 + w[2] + (a ^ b ^ c) + ((e << 5) | (e >> 27))) &
        0xFFFFFFFF;
    a = ((a << 30) | (a >> 2)) & 0xFFFFFFFF;
    final x67 = w[0] ^ w[11] ^ w[5] ^ w[3];
    w[3] = ((x67 << 1) | (x67 >> 31)) & 0xFFFFFFFF;
    c = (c + 0xCA62C1D6 + w[3] + (e ^ a ^ b) + ((d << 5) | (d >> 27))) &
        0xFFFFFFFF;
    e = ((e << 30) | (e >> 2)) & 0xFFFFFFFF;
    final x68 = w[1] ^ w[12] ^ w[6] ^ w[4];
    w[4] = ((x68 << 1) | (x68 >> 31)) & 0xFFFFFFFF;
    b = (b + 0xCA62C1D6 + w[4] + (d ^ e ^ a) + ((c << 5) | (c >> 27))) &
        0xFFFFFFFF;
    d = ((d << 30) | (d >> 2)) & 0xFFFFFFFF;
    final x69 = w[2] ^ w[13] ^ w[7] ^ w[5];
    w[5] = ((x69 << 1) | (x69 >> 31)) & 0xFFFFFFFF;
    a = (a + 0xCA62C1D6 + w[5] + (c ^ d ^ e) + ((b << 5) | (b >> 27))) &
        0xFFFFFFFF;
    c = ((c << 30) | (c >> 2)) & 0xFFFFFFFF;
    final x70 = w[3] ^ w[14] ^ w[8] ^ w[6];
    w[6] = ((x70 << 1) | (x70 >> 31)) & 0xFFFFFFFF;
    e = (e + 0xCA62C1D6 + w[6] + (b ^ c ^ d) + ((a << 5) | (a >> 27))) &
        0xFFFFFFFF;
    b = ((b << 30) | (b >> 2)) & 0xFFFFFFFF;
    final x71 = w[4] ^ w[15] ^ w[9] ^ w[7];
    w[7] = ((x71 << 1) | (x71 >> 31)) & 0xFFFFFFFF;
    d = (d + 0xCA62C1D6 + w[7] + (a ^ b ^ c) + ((e << 5) | (e >> 27))) &
        0xFFFFFFFF;
    a = ((a << 30) | (a >> 2)) & 0xFFFFFFFF;
    final x72 = w[5] ^ w[0] ^ w[10] ^ w[8];
    w[8] = ((x72 << 1) | (x72 >> 31)) & 0xFFFFFFFF;
    c = (c + 0xCA62C1D6 + w[8] + (e ^ a ^ b) + ((d << 5) | (d >> 27))) &
        0xFFFFFFFF;
    e = ((e << 30) | (e >> 2)) & 0xFFFFFFFF;
    final x73 = w[6] ^ w[1] ^ w[11] ^ w[9];
    w[9] = ((x73 << 1) | (x73 >> 31)) & 0xFFFFFFFF;
    b = (b + 0xCA62C1D6 + w[9] + (d ^ e ^ a) + ((c << 5) | (c >> 27))) &
        0xFFFFFFFF;
    d = ((d << 30) | (d >> 2)) & 0xFFFFFFFF;
    final x74 = w[7] ^ w[2] ^ w[12] ^ w[10];
    w[10] = ((x74 << 1) | (x74 >> 31)) & 0xFFFFFFFF;
    a = (a + 0xCA62C1D6 + w[10] + (c ^ d ^ e) + ((b << 5) | (b >> 27))) &
        0xFFFFFFFF;
    c = ((c << 30) | (c >> 2)) & 0xFFFFFFFF;
    final x75 = w[8] ^ w[3] ^ w[13] ^ w[11];
    w[11] = ((x75 << 1) | (x75 >> 31)) & 0xFFFFFFFF;
    e = (e + 0xCA62C1D6 + w[11] + (b ^ c ^ d) + ((a << 5) | (a >> 27))) &
        0xFFFFFFFF;
    b = ((b << 30) | (b >> 2)) & 0xFFFFFFFF;
    final x76 = w[9] ^ w[4] ^ w[14] ^ w[12];
    w[12] = ((x76 << 1) | (x76 >> 31)) & 0xFFFFFFFF;
    d = (d + 0xCA62C1D6 + w[12] + (a ^ b ^ c) + ((e << 5) | (e >> 27))) &
        0xFFFFFFFF;
    a = ((a << 30) | (a >> 2)) & 0xFFFFFFFF;
    final x77 = w[10] ^ w[5] ^ w[15] ^ w[13];
    w[13] = ((x77 << 1) | (x77 >> 31)) & 0xFFFFFFFF;
    c = (c + 0xCA62C1D6 + w[13] + (e ^ a ^ b) + ((d << 5) | (d >> 27))) &
        0xFFFFFFFF;
    e = ((e << 30) | (e >> 2)) & 0xFFFFFFFF;
    final x78 = w[11] ^ w[6] ^ w[0] ^ w[14];
    w[14] = ((x78 << 1) | (x78 >> 31)) & 0xFFFFFFFF;
    b = (b + 0xCA62C1D6 + w[14] + (d ^ e ^ a) + ((c << 5) | (c >> 27))) &
        0xFFFFFFFF;
    d = ((d << 30) | (d >> 2)) & 0xFFFFFFFF;
    final x79 = w[12] ^ w[7] ^ w[1] ^ w[15];
    w[15] = ((x79 << 1) | (x79 >> 31)) & 0xFFFFFFFF;
    a = (a + 0xCA62C1D6 + w[15] + (c ^ d ^ e) + ((b << 5) | (b >> 27))) &
        0xFFFFFFFF;
    c = ((c << 30) | (c >> 2)) & 0xFFFFFFFF;
    h[0] += a;
    h[1] += b;
    h[2] += c;
    h[3] += d;
    h[4] += e;
  }
}
