// Vendored from zpaq-flutter by tool/sync_zpaq.sh: do not edit here, change
// zpaq-flutter and sync again. Pure Dart port of libzpaq and zpaq 7.15 (Matt
// Mahoney, public domain) with the zpaqfranz attribute format (Franco
// Corbelli, MIT). Copyright (c) 2026 Max Brito, BSD 3-clause; see LICENSE
// for the license and the third party notices.

// GENERATED by tool/gen_sais.py. Do not edit.
import 'dart:typed_data';

/// Builds the suffix array of [t] (length [n]) into [sa] using SA-IS.
///
/// The compressor uses divsufsort (divsufsort.dart), which is faster. A
/// suffix array is unique, so this independent implementation serves as
/// its test oracle.
void saisSuffixArray(Uint8List t, Int32List sa, int n) {
  if (n == 0) return;
  if (n == 1) {
    sa[0] = 0;
    return;
  }
  _saisB(t, 0, sa, 0, n, 256);
}

@pragma('vm:unsafe:no-bounds-checks')
void _getBucketsB(Uint8List s, int so, Int32List bkt, int n, int k, bool end) {
  bkt.fillRange(0, k, 0);
  for (var i = 0; i < n; ++i) {
    bkt[s[so + i]]++;
  }
  var sum = 0;
  for (var i = 0; i < k; ++i) {
    sum += bkt[i];
    bkt[i] = end ? sum : sum - bkt[i];
  }
}

@pragma('vm:unsafe:no-bounds-checks')
void _induceB(Uint8List s, int so, Int32List sa, int ao, Uint8List t,
    Int32List bkt, int n, int k) {
  _getBucketsB(s, so, bkt, n, k, false);
  sa[ao + bkt[s[so + n - 1]]++] = n - 1;
  for (var i = 0; i < n; ++i) {
    final j = sa[ao + i] - 1;
    if (j >= 0 && t[j] == 0) sa[ao + bkt[s[so + j]]++] = j;
  }
  _getBucketsB(s, so, bkt, n, k, true);
  for (var i = n - 1; i >= 0; --i) {
    final j = sa[ao + i] - 1;
    if (j >= 0 && t[j] == 1) sa[ao + --bkt[s[so + j]]] = j;
  }
}

// Suffix types: 1 = S, 0 = L. A virtual sentinel smaller than every
// symbol follows the text, so the last suffix is L.
@pragma('vm:unsafe:no-bounds-checks')
void _saisB(Uint8List s, int so, Int32List sa, int ao, int n, int k) {
  final t = Uint8List(n);
  for (var i = n - 2; i >= 0; --i) {
    final a = s[so + i], b = s[so + i + 1];
    t[i] = (a < b || (a == b && t[i + 1] == 1)) ? 1 : 0;
  }
  final bkt = Int32List(k);

  // Step 1: sort LMS substrings.
  _getBucketsB(s, so, bkt, n, k, true);
  sa.fillRange(ao, ao + n, -1);
  for (var i = 1; i < n; ++i) {
    if (t[i] == 1 && t[i - 1] == 0) sa[ao + --bkt[s[so + i]]] = i;
  }
  _induceB(s, so, sa, ao, t, bkt, n, k);

  var n1 = 0;
  for (var i = 0; i < n; ++i) {
    final p = sa[ao + i];
    if (p > 0 && t[p] == 1 && t[p - 1] == 0) sa[ao + n1++] = p;
  }
  sa.fillRange(ao + n1, ao + n, -1);
  // Length of every LMS substring (to the next LMS position, included), in
  // the slot its name goes to. The last one runs into the sentinel: it gets
  // n + 1, a length no other substring has, so it is always a new name.
  var next = -1;
  for (var i = n - 1; i >= 1; --i) {
    if (t[i] == 1 && t[i - 1] == 0) {
      sa[ao + n1 + (i >> 1)] = next < 0 ? n + 1 : next - i + 1;
      next = i;
    }
  }
  // Name them: equal length and equal characters mean equal substrings
  // (the types follow from the characters and the S type at the end).
  var name = 0, prev = -1, plen = 0;
  for (var i = 0; i < n1; ++i) {
    final pos = sa[ao + i];
    final len = sa[ao + n1 + (pos >> 1)];
    var diff = true;
    if (prev >= 0 && len == plen) {
      var d = 0;
      while (d < len && s[so + pos + d] == s[so + prev + d]) {
        ++d;
      }
      diff = d < len;
    }
    if (diff) {
      ++name;
      prev = pos;
      plen = len;
    }
    sa[ao + n1 + (pos >> 1)] = name - 1;
  }
  var j = n - 1;
  for (var i = n - 1; i >= n1; --i) {
    if (sa[ao + i] >= 0) sa[ao + j--] = sa[ao + i];
  }

  // Step 2: solve the reduced problem in place: the reduced string is in
  // sa[n-n1..n), its suffix array goes to sa[0..n1) (n1 <= n/2).
  if (name < n1) {
    _saisI(sa, ao + n - n1, sa, ao, n1, name);
  } else {
    for (var i = 0; i < n1; ++i) {
      sa[ao + sa[ao + n - n1 + i]] = i;
    }
  }

  // Step 3: induce the final order from the sorted LMS suffixes.
  j = n - n1;
  for (var i = 1; i < n; ++i) {
    if (t[i] == 1 && t[i - 1] == 0) sa[ao + j++] = i; // LMS, text order
  }
  for (var i = 0; i < n1; ++i) {
    sa[ao + i] = sa[ao + n - n1 + sa[ao + i]];
  }
  sa.fillRange(ao + n1, ao + n, -1);
  _getBucketsB(s, so, bkt, n, k, true);
  for (var i = n1 - 1; i >= 0; --i) {
    final p = sa[ao + i];
    sa[ao + i] = -1;
    sa[ao + --bkt[s[so + p]]] = p;
  }
  _induceB(s, so, sa, ao, t, bkt, n, k);
}

@pragma('vm:unsafe:no-bounds-checks')
void _getBucketsI(Int32List s, int so, Int32List bkt, int n, int k, bool end) {
  bkt.fillRange(0, k, 0);
  for (var i = 0; i < n; ++i) {
    bkt[s[so + i]]++;
  }
  var sum = 0;
  for (var i = 0; i < k; ++i) {
    sum += bkt[i];
    bkt[i] = end ? sum : sum - bkt[i];
  }
}

@pragma('vm:unsafe:no-bounds-checks')
void _induceI(Int32List s, int so, Int32List sa, int ao, Uint8List t,
    Int32List bkt, int n, int k) {
  _getBucketsI(s, so, bkt, n, k, false);
  sa[ao + bkt[s[so + n - 1]]++] = n - 1;
  for (var i = 0; i < n; ++i) {
    final j = sa[ao + i] - 1;
    if (j >= 0 && t[j] == 0) sa[ao + bkt[s[so + j]]++] = j;
  }
  _getBucketsI(s, so, bkt, n, k, true);
  for (var i = n - 1; i >= 0; --i) {
    final j = sa[ao + i] - 1;
    if (j >= 0 && t[j] == 1) sa[ao + --bkt[s[so + j]]] = j;
  }
}

// Suffix types: 1 = S, 0 = L. A virtual sentinel smaller than every
// symbol follows the text, so the last suffix is L.
@pragma('vm:unsafe:no-bounds-checks')
void _saisI(Int32List s, int so, Int32List sa, int ao, int n, int k) {
  final t = Uint8List(n);
  for (var i = n - 2; i >= 0; --i) {
    final a = s[so + i], b = s[so + i + 1];
    t[i] = (a < b || (a == b && t[i + 1] == 1)) ? 1 : 0;
  }
  final bkt = Int32List(k);

  // Step 1: sort LMS substrings.
  _getBucketsI(s, so, bkt, n, k, true);
  sa.fillRange(ao, ao + n, -1);
  for (var i = 1; i < n; ++i) {
    if (t[i] == 1 && t[i - 1] == 0) sa[ao + --bkt[s[so + i]]] = i;
  }
  _induceI(s, so, sa, ao, t, bkt, n, k);

  var n1 = 0;
  for (var i = 0; i < n; ++i) {
    final p = sa[ao + i];
    if (p > 0 && t[p] == 1 && t[p - 1] == 0) sa[ao + n1++] = p;
  }
  sa.fillRange(ao + n1, ao + n, -1);
  // Length of every LMS substring (to the next LMS position, included), in
  // the slot its name goes to. The last one runs into the sentinel: it gets
  // n + 1, a length no other substring has, so it is always a new name.
  var next = -1;
  for (var i = n - 1; i >= 1; --i) {
    if (t[i] == 1 && t[i - 1] == 0) {
      sa[ao + n1 + (i >> 1)] = next < 0 ? n + 1 : next - i + 1;
      next = i;
    }
  }
  // Name them: equal length and equal characters mean equal substrings
  // (the types follow from the characters and the S type at the end).
  var name = 0, prev = -1, plen = 0;
  for (var i = 0; i < n1; ++i) {
    final pos = sa[ao + i];
    final len = sa[ao + n1 + (pos >> 1)];
    var diff = true;
    if (prev >= 0 && len == plen) {
      var d = 0;
      while (d < len && s[so + pos + d] == s[so + prev + d]) {
        ++d;
      }
      diff = d < len;
    }
    if (diff) {
      ++name;
      prev = pos;
      plen = len;
    }
    sa[ao + n1 + (pos >> 1)] = name - 1;
  }
  var j = n - 1;
  for (var i = n - 1; i >= n1; --i) {
    if (sa[ao + i] >= 0) sa[ao + j--] = sa[ao + i];
  }

  // Step 2: solve the reduced problem in place: the reduced string is in
  // sa[n-n1..n), its suffix array goes to sa[0..n1) (n1 <= n/2).
  if (name < n1) {
    _saisI(sa, ao + n - n1, sa, ao, n1, name);
  } else {
    for (var i = 0; i < n1; ++i) {
      sa[ao + sa[ao + n - n1 + i]] = i;
    }
  }

  // Step 3: induce the final order from the sorted LMS suffixes.
  j = n - n1;
  for (var i = 1; i < n; ++i) {
    if (t[i] == 1 && t[i - 1] == 0) sa[ao + j++] = i; // LMS, text order
  }
  for (var i = 0; i < n1; ++i) {
    sa[ao + i] = sa[ao + n - n1 + sa[ao + i]];
  }
  sa.fillRange(ao + n1, ao + n, -1);
  _getBucketsI(s, so, bkt, n, k, true);
  for (var i = n1 - 1; i >= 0; --i) {
    final p = sa[ao + i];
    sa[ao + i] = -1;
    sa[ao + --bkt[s[so + p]]] = p;
  }
  _induceI(s, so, sa, ao, t, bkt, n, k);
}
