// Regenerates lib/src/codec/zcm/zcm_dict_words.dart, the word list of the
// zcm dictionary transform, from cmix's english.dic:
//
//   dart run tool/zcm_gen_dict.dart [ref/cmix/dictionary/english.dic]
//
// The words are stored raw DEFLATE compressed (level 9, lib/src/codec/
// deflate) and base64 encoded in a const String; zcm_dict.dart inflates
// them on first use. The inflated bytes must equal english.dic: the
// dictionary codes of every zcm stream depend on the order of the words.

import 'dart:convert';
import 'dart:io';

import 'package:zx/src/codec/deflate/deflate_coder.dart';

void main(List<String> args) {
  final src = args.isEmpty ? 'ref/cmix/dictionary/english.dic' : args[0];
  final raw = File(src).readAsBytesSync();
  final packed = deflateBytes(raw, level: 9);
  final back = inflateBytes(packed);
  if (back.length != raw.length) throw StateError('inflate mismatch');
  for (var i = 0; i < raw.length; i++) {
    if (back[i] != raw[i]) throw StateError('inflate mismatch at $i');
  }
  var words = 0;
  for (final b in raw) {
    if (b == 0x0A) words++;
  }
  final b64 = base64.encode(packed);
  final out = StringBuffer()
    ..writeln('// zcm: the word list of the dictionary transform '
        '(zcm_dict.dart).')
    ..writeln('//')
    ..writeln('// english.dic of cmix (Byron Knoll): ${_group(words)} '
        'English words in lowercase,')
    ..writeln('// most frequent first, one per line. Stored here raw DEFLATE '
        'compressed')
    ..writeln('// and base64 encoded (${raw.length} bytes of words, '
        '${packed.length} compressed).')
    ..writeln('// Generated by tool/zcm_gen_dict.dart from '
        'ref/cmix/dictionary/english.dic;')
    ..writeln('// do not edit.')
    ..writeln()
    ..writeln("import 'dart:convert';")
    ..writeln("import 'dart:typed_data';")
    ..writeln()
    ..writeln("import '../deflate/deflate_coder.dart';")
    ..writeln()
    ..writeln('/// english.dic: the words in their order, one per line.')
    ..writeln('Uint8List zcmDictBytes() =>')
    ..writeln('    inflateBytes(Uint8List.fromList(base64.decode(_data)));')
    ..writeln()
    ..writeln('const String _data =');
  for (var i = 0; i < b64.length; i += 76) {
    final end = i + 76 < b64.length ? i + 76 : b64.length;
    out.write("    '${b64.substring(i, end)}'");
    out.writeln(end == b64.length ? ';' : '');
  }
  File('lib/src/codec/zcm/zcm_dict_words.dart')
      .writeAsStringSync(out.toString());
  stdout.writeln('${raw.length} bytes, ${packed.length} deflated, '
      '${b64.length} base64');
}

String _group(int n) {
  final s = n.toString();
  final b = StringBuffer();
  for (var i = 0; i < s.length; i++) {
    if (i > 0 && (s.length - i) % 3 == 0) b.write(',');
    b.write(s[i]);
  }
  return b.toString();
}
